#!/usr/bin/env python3
"""Build the deterministic, human-interface data bundle from canonical records."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "site" / "data" / "context.bundle.js"
MANIFEST = ROOT / "site" / "data" / "projection-manifest.json"
INPUTS = {
    "profile": ROOT / "profiles" / "sabine-public.json",
    "research": ROOT / "research" / "current-focus.json",
    "publications": ROOT / "publications" / "index.json",
    "sources": ROOT / "sources" / "public-sources.json",
}


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def canonical_inputs() -> list[dict[str, str]]:
    return [
        {
            "path": str(path.relative_to(ROOT)),
            "sha256": sha256_bytes(path.read_bytes()),
        }
        for path in INPUTS.values()
    ]


def render() -> tuple[str, str]:
    inputs = canonical_inputs()
    canonical_fingerprint = sha256_bytes(
        "".join(f"{item['path']}\t{item['sha256']}\n" for item in inputs).encode("utf-8")
    )
    generator_path = Path(__file__).resolve()
    projection = {
        "kind": "deterministic_human_interface_projection",
        "canonical_source_of_truth": "canonical public records in the sabine-gpt repository",
        "canonical_inputs": inputs,
        "canonical_fingerprint_sha256": canonical_fingerprint,
        "generator": str(generator_path.relative_to(ROOT)),
        "generator_sha256": sha256_bytes(generator_path.read_bytes()),
        "build_timestamp": None,
        "reproducibility_note": "No wall-clock value or environment-specific path is included; identical canonical bytes and generator bytes produce identical artifacts.",
    }
    payload = {
        "bundle_type": "sabine-research-desk-public-snapshot",
        "bundle_version": "1.0.0",
        "projection": projection,
        **{name: load(path) for name, path in INPUTS.items()},
    }
    encoded = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    bundle = (
        "/* Generated by tools/build_site_data.py. Do not edit by hand. */\n"
        "window.SABINE_RESEARCH_DESK = "
        f"{encoded};\n"
    )
    manifest = {
        "type": "sabine-research-desk-projection-manifest",
        "schema_version": "1.0.0",
        "projection_kind": projection["kind"],
        "canonical_source_of_truth": projection["canonical_source_of_truth"],
        "canonical_inputs": inputs,
        "canonical_fingerprint_sha256": canonical_fingerprint,
        "generator": projection["generator"],
        "generator_sha256": projection["generator_sha256"],
        "artifacts": [
            {
                "path": str(OUTPUT.relative_to(ROOT)),
                "sha256": sha256_bytes(bundle.encode("utf-8")),
            }
        ],
        "authority": "projection_only",
        "inspection_rule": "Trace every displayed claim to a canonical record and its own public source; do not infer support by adjacency.",
    }
    return bundle, f"{json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True)}\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in bundle differs from canonical records",
    )
    args = parser.parse_args()
    expected_bundle, expected_manifest = render()

    if args.check:
        stale = (
            not OUTPUT.is_file()
            or OUTPUT.read_text(encoding="utf-8") != expected_bundle
            or not MANIFEST.is_file()
            or MANIFEST.read_text(encoding="utf-8") != expected_manifest
        )
        if stale:
            raise SystemExit(
                "site projection artifacts are stale; run: python3 tools/build_site_data.py"
            )
        print("sabine research desk projection bundle and manifest: current")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected_bundle, encoding="utf-8")
    MANIFEST.write_text(expected_manifest, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} and {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
